name: ProcessRequest

on:
  issues:
    types: [opened]

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

  process_image:
    name: Process image
#    needs: [test, lint]
#    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/processImage.yml
    secrets: inherit
    with:
      imageUrl: https://cdn.discordapp.com/attachments/913387055596326952/1072648112692285471/GODS.png
  add_image:
    runs-on: ubuntu-latest
    needs: process_image
    if: ${{ contains(github.event.labels.*.name, 'addImage') }}
    steps:
      - run: echo ${{ needs.process_image.outputs.imageBin }}